DROP TABLE IF EXISTS API_KEY;

CREATE TABLE API_KEY (
    ID              NUMBER NOT NULL,
    KEY             VARCHAR (50) NOT NULL,
    USERNAME        VARCHAR(50) NOT NULL ,
    PASSWORD        VARCHAR(50) NOT NULL ,
    ROLE            VARCHAR(50) NOT NULL ,
    PRIMARY KEY ("ID")
);